#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu May 23 07:20:20 2019

@author: manpreetsaluja
"""
#LIST OPERATIONS

list1=['nikhil','excelr',2013,2014]
print(list1[0][1])
#ouput nikhil 1st index 
#indexing starts from 0

list2=[1,2,3,4,5,6,7,8]
print(list2[0:5])

#remmeber python use n-1

#UPDATE LIST
list1[0]=1
print(list1)

#DELETE LIST
del(list1[0])

#TYPE
type(list1)


#Append
list1.append(3739832)
print(list1)

#Pop
print(list1.pop(1))
print(list1)

#extend
print(list1.extend(list2))
print(list1)


#insert
list1.insert(1,2019)

#reverse
list1.reverse()
 print(list1)
 
 #sort
 list.sort()
 
 #count
 print(list1.count("2"))